version: '3.8'
services:
  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"  # Ana API ucu
    environment:
      - SERVICES=s3,dynamodb,lambda,sts,s3control,iam,logs  # Kullanacağın AWS servisleri
      - DEBUG=1
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - LOCALSTACK_AUTH_TOKEN=your-token-here  # LocalStack Pro özelliklerini kullanmak için
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"